//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SourceControl.Models.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADPermission
    {
        public int ID { get; set; }
        public string ADGroup { get; set; }
        public string LoadBalancer { get; set; }
        public string PoolName { get; set; }
        public System.DateTime DateGranted { get; set; }
        public string GrantedBy { get; set; }
    }
}
