//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SourceControl.Models.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppUser
    {
        public int UserId { get; set; }
        public bool IsActive { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string FullName { get; set; }
        public string Email { get; set; }
        public string PrimaryPhone { get; set; }
        public string AdName { get; set; }
        public string Password { get; set; }
        public bool ProfileIsComplete { get; set; }
        public int LogonCount { get; set; }
        public string RoleNames { get; set; }
        public string RoleIds { get; set; }
        public string RoleMenuIds { get; set; }
        public System.DateTime AddDate { get; set; }
    }
}
