//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SourceControl.Models.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class CertFile
    {
        public System.Guid guid { get; set; }
        public System.Guid jobguid { get; set; }
        public string f5HostName { get; set; }
        public string kind { get; set; }
        public string name { get; set; }
        public string partition { get; set; }
        public string fullPath { get; set; }
        public Nullable<long> generation { get; set; }
        public string selfLink { get; set; }
        public string certificateKeyCurveName { get; set; }
        public Nullable<long> certificateKeySize { get; set; }
        public string checksum { get; set; }
        public string createTime { get; set; }
        public string createdBy { get; set; }
        public Nullable<long> expirationDate { get; set; }
        public string expiration { get; set; }
        public string isBundle { get; set; }
        public string issuer { get; set; }
        public string keyType { get; set; }
        public string lastUpdateTime { get; set; }
        public Nullable<long> mode { get; set; }
        public Nullable<long> revision { get; set; }
        public string serialNumber { get; set; }
        public Nullable<long> size { get; set; }
        public string subject { get; set; }
        public string subjectAlternativeName { get; set; }
        public string updatedBy { get; set; }
        public Nullable<long> version { get; set; }
        public string systemPath { get; set; }
        public string email { get; set; }
        public string BundleCertificatesReferencelink { get; set; }
        public Nullable<bool> BundleCertificatesReferenceisSubcollection { get; set; }
    }
}
