//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SourceControl.Models.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientSSLCertKeyChain
    {
        public System.Guid guid { get; set; }
        public System.Guid jobguid { get; set; }
        public string f5hostname { get; set; }
        public System.Guid CertGuid { get; set; }
        public string name { get; set; }
        public string cert { get; set; }
        public string chain { get; set; }
        public string key { get; set; }
    }
}
