//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SourceControl.Models.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public int ClientId { get; set; }
        public string ClientName { get; set; }
        public int ChangeBy { get; set; }
        public System.DateTime ChangeDate { get; set; }
        public int AddBy { get; set; }
        public System.DateTime AddDate { get; set; }
    }
}
