//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SourceControl.Models.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactDB
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Number1 { get; set; }
        public string Number2 { get; set; }
        public string Email { get; set; }
        public string ENOTE { get; set; }
        public string EsscalationContact { get; set; }
        public string EsscalationNumber { get; set; }
        public string Notes { get; set; }
    }
}
