//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SourceControl.Models.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomOption
    {
        public int CustomOptionId { get; set; }
        public int ColumnDefId { get; set; }
        public string OptionText { get; set; }
        public string OptionValue { get; set; }
    }
}
