//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SourceControl.Models.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Device
    {
        public string DeviceName { get; set; }
        public string Type { get; set; }
        public string Model { get; set; }
        public string SerialNum { get; set; }
        public string MGMTIP { get; set; }
        public string Comments { get; set; }
        public string FloorLoc { get; set; }
        public string DataCenter { get; set; }
        public string Module { get; set; }
        public string Zone { get; set; }
        public string Path { get; set; }
    }
}
