//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SourceControl.Models.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeviceData
    {
        public System.Guid guid { get; set; }
        public Nullable<System.Guid> jobguid { get; set; }
        public string kind { get; set; }
        public string name { get; set; }
        public string partition { get; set; }
        public string fullPath { get; set; }
        public Nullable<long> generation { get; set; }
        public string selfLink { get; set; }
        public string activeModules { get; set; }
        public string baseMac { get; set; }
        public string build { get; set; }
        public string cert { get; set; }
        public string chassisId { get; set; }
        public string chassisType { get; set; }
        public string configsyncIp { get; set; }
        public string edition { get; set; }
        public string failoverState { get; set; }
        public Nullable<long> haCapacity { get; set; }
        public string hostname { get; set; }
        public string devicekey { get; set; }
        public string managementIp { get; set; }
        public string marketingName { get; set; }
        public string mirrorIp { get; set; }
        public string mirrorSecondaryIp { get; set; }
        public string multicastIp { get; set; }
        public Nullable<long> multicastPort { get; set; }
        public string optionalModules { get; set; }
        public string platformId { get; set; }
        public string product { get; set; }
        public string selfDevice { get; set; }
        public string timeZone { get; set; }
        public string version { get; set; }
        public string unicastAddress { get; set; }
    }
}
