//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SourceControl.Models.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeviceGroupTask
    {
        public System.Guid guid { get; set; }
        public System.Guid groupguid { get; set; }
        public string taskname { get; set; }
        public System.DateTime taskstart { get; set; }
        public System.DateTime taskend { get; set; }
        public string comments { get; set; }
    }
}
