//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SourceControl.Models.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class eVPN
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public string mgt { get; set; }
        public string Lo0 { get; set; }
        public string Lo1 { get; set; }
        public string secondary { get; set; }
        public string E1a { get; set; }
        public string E1b { get; set; }
        public string ASN { get; set; }
        public string VPC { get; set; }
        public string router { get; set; }
        public string bgp { get; set; }
        public string SWS1_2 { get; set; }
        public string SWS3_4 { get; set; }
        public string Notes { get; set; }
    }
}
