//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SourceControl.Models.Db
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AppF5DataEntities : DbContext
    {
        public AppF5DataEntities()
            : base("name=AppF5DataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<App> Apps { get; set; }
        public virtual DbSet<Cert> Certs { get; set; }
        public virtual DbSet<CertFile> CertFiles { get; set; }
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<ClientSSL> ClientSSLs { get; set; }
        public virtual DbSet<ClientSSLCertKeyChain> ClientSSLCertKeyChains { get; set; }
        public virtual DbSet<CustomOption> CustomOptions { get; set; }
        public virtual DbSet<DeviceData> DeviceDatas { get; set; }
        public virtual DbSet<Irule> Irules { get; set; }
        public virtual DbSet<IruleApiRawValues2> IruleApiRawValues2 { get; set; }
        public virtual DbSet<JobLog> JobLogs { get; set; }
        public virtual DbSet<JobLogTask> JobLogTasks { get; set; }
        public virtual DbSet<MasterDeviceList> MasterDeviceLists { get; set; }
        public virtual DbSet<MonitorHttp> MonitorHttps { get; set; }
        public virtual DbSet<NatTranslation> NatTranslations { get; set; }
        public virtual DbSet<Node> Nodes { get; set; }
        public virtual DbSet<NodeFqdn> NodeFqdns { get; set; }
        public virtual DbSet<Pool> Pools { get; set; }
        public virtual DbSet<PoolMember> PoolMembers { get; set; }
        public virtual DbSet<PoolMembersReference> PoolMembersReferences { get; set; }
        public virtual DbSet<Route> Routes { get; set; }
        public virtual DbSet<SelfIP> SelfIPs { get; set; }
        public virtual DbSet<SNATPool> SNATPools { get; set; }
        public virtual DbSet<VipPersist> VipPersists { get; set; }
        public virtual DbSet<VIPPersistDetail> VIPPersistDetails { get; set; }
        public virtual DbSet<VIPPoliciesReference> VIPPoliciesReferences { get; set; }
        public virtual DbSet<VipProfilesDetail> VipProfilesDetails { get; set; }
        public virtual DbSet<VIPProfilesReference> VIPProfilesReferences { get; set; }
        public virtual DbSet<VIPStat> VIPStats { get; set; }
        public virtual DbSet<VLAN> VLANs { get; set; }
        public virtual DbSet<VIP> VIPs { get; set; }
    }
}
