//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SourceControl.Models.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class F5Pool
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public F5Pool()
        {
            this.PoolMemberInfoForWebs = new HashSet<PoolMemberInfoForWeb>();
        }
    
        public int F5PoolId { get; set; }
        public string DeviceName { get; set; }
        public string Name { get; set; }
        public string LoadBalancingMode { get; set; }
        public string Monitor { get; set; }
        public string StatusAvailabilityState { get; set; }
        public string StatusEnabledState { get; set; }
        public string StatusStatusReason { get; set; }
        public string CurSessions { get; set; }
        public string TotRequests { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PoolMemberInfoForWeb> PoolMemberInfoForWebs { get; set; }
    }
}
