//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SourceControl.Models.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class FWNat
    {
        public System.Guid guid { get; set; }
        public string FirewallName { get; set; }
        public string type { get; set; }
        public string source { get; set; }
        public string destination { get; set; }
        public string direction { get; set; }
    }
}
