//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SourceControl.Models.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class FWRoute
    {
        public System.Guid guid { get; set; }
        public string Network { get; set; }
        public string CMSFirewallIP { get; set; }
        public string CMSFirewall { get; set; }
        public string InternetFirewallIP { get; set; }
        public string InternetFirewall { get; set; }
        public string Environment { get; set; }
        public string Notes { get; set; }
    }
}
