//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SourceControl.Models.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class HPNA_DEVICE_VLAN_INFO
    {
        public int DeviceVlanInfoID { get; set; }
        public int DeviceID { get; set; }
        public int VlanID { get; set; }
        public string VlanName { get; set; }
        public string VlanType { get; set; }
        public string VlanPrivate { get; set; }
        public string Mtu { get; set; }
        public string VlanStatus { get; set; }
        public string Description { get; set; }
        public string LastModifiedUserID { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
    }
}
