//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SourceControl.Models.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class HPNA_DEVICE_MODULE
    {
        public double DeviceModuleID { get; set; }
        public Nullable<double> DeviceID { get; set; }
        public string Slot { get; set; }
        public string ModuleModel { get; set; }
        public string ModuleDescription { get; set; }
        public string ModuleOS { get; set; }
        public string FirmwareVersion { get; set; }
        public string HardwareRevision { get; set; }
        public string Memory { get; set; }
        public string ModuleCustom1 { get; set; }
        public string ModuleCustom2 { get; set; }
        public string ModuleCustom3 { get; set; }
        public string ModuleCustom4 { get; set; }
        public string ModuleCustom5 { get; set; }
        public string ModuleCustom6 { get; set; }
        public string Comments { get; set; }
        public string SerialNumber { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public Nullable<double> SlotNumber { get; set; }
        public string ChildDeviceID { get; set; }
        public Nullable<double> Status { get; set; }
        public string SlotType { get; set; }
        public string Parent { get; set; }
    }
}
