//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SourceControl.Models.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class HPNA_DEVICE
    {
        public double DeviceID { get; set; }
        public string PrimaryIPAddress { get; set; }
        public string PrimaryFQDN { get; set; }
        public string HostName { get; set; }
        public string DeviceName { get; set; }
        public string SerialNumber { get; set; }
        public string AssetTag { get; set; }
        public string SoftwareVersion { get; set; }
        public string FirmwareVersion { get; set; }
        public string Vendor { get; set; }
        public string Model { get; set; }
        public string DeviceType { get; set; }
        public string GeographicalLocation { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> LastAccessAttemptDate { get; set; }
        public Nullable<System.DateTime> LastAccessSuccessDate { get; set; }
        public Nullable<System.DateTime> LastSnapshotDate { get; set; }
        public string LastAccessAttemptStatus { get; set; }
        public Nullable<double> LastModifiedUserID { get; set; }
        public Nullable<double> ExcludeFromPoll { get; set; }
        public string AccessMethods { get; set; }
        public string ModemNumber { get; set; }
        public Nullable<double> ManagementStatus { get; set; }
        public string FeedSource { get; set; }
        public string LastImportDate { get; set; }
        public string ChangeEventData { get; set; }
        public Nullable<double> MostRecentConfigID { get; set; }
        public Nullable<double> LastConfigChangeUserID { get; set; }
        public Nullable<System.DateTime> LastRecordModifiedDate { get; set; }
        public Nullable<double> LatestStartupRunningDiffer { get; set; }
        public string DeviceCustom1 { get; set; }
        public string DeviceCustom2 { get; set; }
        public string DeviceCustom3 { get; set; }
        public string DeviceCustom4 { get; set; }
        public string DeviceCustom5 { get; set; }
        public string DeviceCustom6 { get; set; }
        public Nullable<double> Memory { get; set; }
        public string FlashMemory { get; set; }
        public Nullable<double> TotalPorts { get; set; }
        public Nullable<double> FreePorts { get; set; }
        public string PutInServiceDate { get; set; }
        public string UnmanagedDate { get; set; }
        public string ROMVersion { get; set; }
        public string Processor { get; set; }
        public Nullable<double> LatestSoftwareHistoryID { get; set; }
        public Nullable<System.DateTime> LastConfigPolicyCheckedDate { get; set; }
        public Nullable<double> LastUsedAuthenticationID { get; set; }
        public Nullable<System.DateTime> LastSnapshotAttemptDate { get; set; }
        public Nullable<System.DateTime> LastSnapshotSuccessDate { get; set; }
        public string LastSnapshotAttemptStatus { get; set; }
        public string TicketNumber { get; set; }
        public Nullable<double> PerformACLParsing { get; set; }
        public Nullable<double> Uptime { get; set; }
        public Nullable<System.DateTime> UptimeStoredDate { get; set; }
        public Nullable<double> PolicyInCompliance { get; set; }
        public string PolicyImportance { get; set; }
        public Nullable<double> SiteID { get; set; }
        public string HierarchyLayer { get; set; }
        public Nullable<double> DeviceGroup1ID { get; set; }
        public string DeviceGroup2ID { get; set; }
        public string DeviceGroup3ID { get; set; }
        public Nullable<System.DateTime> LastTopologyDataUpdate { get; set; }
        public Nullable<System.DateTime> LastDuplexDataUpdate { get; set; }
        public string Contact { get; set; }
        public Nullable<double> DuplexMismatchDetected { get; set; }
    }
}
