//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SourceControl.Models.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class IPNetwork
    {
        public System.Guid guid { get; set; }
        public string Site { get; set; }
        public string ApplicationEnvironment { get; set; }
        public string Subnet { get; set; }
        public string IPv4DefaultGateway { get; set; }
        public string MASK { get; set; }
        public string IPv6 { get; set; }
        public string IPv6DefaultGateway { get; set; }
        public string VLAN { get; set; }
        public string ASSIGNMENT { get; set; }
        public string VRF { get; set; }
        public string NetworkDevice { get; set; }
        public string MonitoringDevice { get; set; }
        public string Notes { get; set; }
        public string Color { get; set; }
    }
}
