//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SourceControl.Models.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Irule
    {
        public System.Guid guid { get; set; }
        public Nullable<System.Guid> jobguid { get; set; }
        public string f5HostName { get; set; }
        public string kind { get; set; }
        public string name { get; set; }
        public string partition { get; set; }
        public string fullpath { get; set; }
        public Nullable<long> generation { get; set; }
        public string selfLink { get; set; }
        public string apiAnonymous { get; set; }
        public Nullable<System.Guid> apiRawValuesGuid { get; set; }
    }
}
