//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SourceControl.Models.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class LBPoolMember
    {
        public System.Guid GUID { get; set; }
        public System.Guid VIPGUID { get; set; }
        public int RequestNumber { get; set; }
        public string ServerName { get; set; }
        public string ServerIPv4 { get; set; }
        public int ServerPort { get; set; }
        public string ServerIPv6 { get; set; }
        public string PoolName { get; set; }
    }
}
