//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SourceControl.Models.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class LBVIPRequest
    {
        public System.Guid GUID { get; set; }
        public int RequestNumber { get; set; }
        public string ApplicationName { get; set; }
        public string VIPName { get; set; }
        public string VIPIP { get; set; }
        public Nullable<int> VIPPort { get; set; }
        public string VIPIPv6 { get; set; }
        public string ExternalIP { get; set; }
        public Nullable<int> ExternalPort { get; set; }
        public string ExternalURL { get; set; }
        public string ProfileType { get; set; }
        public string Persistence { get; set; }
        public string PoolName { get; set; }
        public string PoolMonitor { get; set; }
        public string SnatPoolName { get; set; }
        public string Environment { get; set; }
        public string DCLocation { get; set; }
        public string Notes { get; set; }
    }
}
