//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SourceControl.Models.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class MasterDeviceList
    {
        public System.Guid guid { get; set; }
        public string DeviceName { get; set; }
        public string mgmtIP { get; set; }
        public bool active { get; set; }
        public string pairName { get; set; }
        public bool enabled { get; set; }
    }
}
