//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SourceControl.Models.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class MasterDevice
    {
        public string HostName { get; set; }
        public System.Guid DeviceGUID { get; set; }
        public string DeviceIP { get; set; }
        public string DeviceVendor { get; set; }
        public string DeviceModel { get; set; }
        public string DeviceLocation { get; set; }
        public string RackUnit { get; set; }
        public string SerialNumber { get; set; }
        public string SRFU { get; set; }
        public string Site { get; set; }
        public string Checklist { get; set; }
        public string Zone { get; set; }
        public string Path { get; set; }
        public string DeviceType { get; set; }
        public string LastImport { get; set; }
        public string Comments { get; set; }
        public string API { get; set; }
        public string PortCountStat { get; set; }
    }
}
