//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SourceControl.Models.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class MonitorHttp
    {
        public System.Guid guid { get; set; }
        public Nullable<System.Guid> jobguid { get; set; }
        public string f5HostName { get; set; }
        public string kind { get; set; }
        public string name { get; set; }
        public string partition { get; set; }
        public string fullpath { get; set; }
        public Nullable<long> generation { get; set; }
        public string selfLink { get; set; }
        public string adaptive { get; set; }
        public string adaptiveDivergenceType { get; set; }
        public Nullable<long> adaptiveDivergenceValue { get; set; }
        public Nullable<long> adaptiveLimit { get; set; }
        public Nullable<long> adaptiveSamplingTimespan { get; set; }
        public string defaultsFrom { get; set; }
        public string destination { get; set; }
        public Nullable<long> interval { get; set; }
        public Nullable<long> ipDscp { get; set; }
        public string manualResume { get; set; }
        public string recv { get; set; }
        public string reverse { get; set; }
        public string send { get; set; }
        public Nullable<long> timeUntilUp { get; set; }
        public Nullable<long> timeout { get; set; }
        public string transparent { get; set; }
        public Nullable<long> upInterval { get; set; }
    }
}
