//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SourceControl.Models.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class NatTranslation
    {
        public int NatTranslationId { get; set; }
        public string FirewallName { get; set; }
        public string RuleName { get; set; }
        public string RuleSetName { get; set; }
        public Nullable<int> RuleId { get; set; }
        public Nullable<int> RuleMatchingPosition { get; set; }
        public string RuleFromContext { get; set; }
        public string RuleFromContextName { get; set; }
        public string RuleDestinationAddressPrefix { get; set; }
        public Nullable<int> RuleDestinationPortLow { get; set; }
        public Nullable<int> RuleDestinationPortHigh { get; set; }
        public string RuleHostAddressPrefix { get; set; }
        public Nullable<int> RuleHostPortLow { get; set; }
        public Nullable<int> RuleHostPortHigh { get; set; }
        public string RuleAddressNetmask { get; set; }
        public string RuleHostRoutingInstance { get; set; }
        public Nullable<int> RuleTranslationHits { get; set; }
        public Nullable<int> SuccHits { get; set; }
        public Nullable<int> FailedHits { get; set; }
        public Nullable<int> ConcurrentHits { get; set; }
        public string UploadFile { get; set; }
        public Nullable<System.DateTime> FileDate { get; set; }
    }
}
