//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SourceControl.Models.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class NodeFqdn
    {
        public System.Guid guid { get; set; }
        public System.Guid jobguid { get; set; }
        public System.Guid nodeguid { get; set; }
        public string nodename { get; set; }
        public string f5hostname { get; set; }
        public string addressFamily { get; set; }
        public string autopopulate { get; set; }
        public Nullable<long> downInterval { get; set; }
        public Nullable<long> interval { get; set; }
    }
}
