//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SourceControl.Models.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class PageTemplate
    {
        public int PageTemplateId { get; set; }
        public int DbEntityId { get; set; }
        public string TemplateName { get; set; }
        public string TableName { get; set; }
        public string GridColumns { get; set; }
        public string SortColumns { get; set; }
        public string AddTabLabel { get; set; }
        public string ViewTabLabel { get; set; }
        public string EditTabLabel { get; set; }
        public string EditLayout { get; set; }
        public string ViewLayout { get; set; }
        public string PageType { get; set; }
        public string FilterClause { get; set; }
        public int HelpId { get; set; }
        public string OnLoadScript { get; set; }
        public string BodyScript { get; set; }
        public string OnSaveScript { get; set; }
        public int PageTemplateId2 { get; set; }
        public int RefKey2 { get; set; }
        public int PrimaryKey2 { get; set; }
        public string GridStyle { get; set; }
        public string GridCommand { get; set; }
        public string GridBody { get; set; }
        public string GridScript { get; set; }
        public string GridOnDataBound { get; set; }
        public string CustomEditForm { get; set; }
        public string GroupByColumns { get; set; }
        public bool GridAutoBind { get; set; }
        public string RefKey2Name { get; set; }
        public string PrimaryKey2Name { get; set; }
        public string SearchLayout { get; set; }
        public string ViewFormStyle { get; set; }
        public string ViewFormCommand { get; set; }
        public string ViewFormBody { get; set; }
        public string ViewFormScript { get; set; }
        public string EditFormStyle { get; set; }
        public string EditFormCommand { get; set; }
        public string EditFormBody { get; set; }
        public string EditFormScript { get; set; }
        public string SearchFormStyle { get; set; }
        public string SearchFormCommand { get; set; }
        public string SearchFormBody { get; set; }
        public string SearchFormScript { get; set; }
        public string ReportGridColumns { get; set; }
        public string FormCommand { get; set; }
        public string FormScript { get; set; }
    }
}
