//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SourceControl.Models.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class PoolMemberInfoForWeb
    {
        public int id { get; set; }
        public string poolName { get; set; }
        public string deviceName { get; set; }
        public string nodeName { get; set; }
        public string serversidebitsIn { get; set; }
        public string serversidebitsOut { get; set; }
        public string serversidecurConns { get; set; }
        public string serversidemaxConns { get; set; }
        public string serversidepktsIn { get; set; }
        public string serversidepktsOut { get; set; }
        public string serversidetotConns { get; set; }
        public string sessionStatus { get; set; }
        public string statusavailabilityState { get; set; }
        public string statusenabledState { get; set; }
        public string statusstatusReason { get; set; }
        public string totRequests { get; set; }
        public string port { get; set; }
        public string addr { get; set; }
        public string connqageEdm { get; set; }
        public string connqageEma { get; set; }
        public string connqageHead { get; set; }
        public string connqageMax { get; set; }
        public string connqdepth { get; set; }
        public string connqserviced { get; set; }
        public string curSessions { get; set; }
        public string monitorRule { get; set; }
        public string monitorStatus { get; set; }
        public int F5PoolId { get; set; }
    }
}
