//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SourceControl.Models.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        public int RequestNumber { get; set; }
        public string RequestType { get; set; }
        public string AMD { get; set; }
        public string Requester { get; set; }
        public string TicketNumber { get; set; }
        public string XOCArt { get; set; }
        public string EngineerOwner { get; set; }
        public Nullable<System.DateTime> RequestedImpDate { get; set; }
        public Nullable<System.DateTime> DateSubmitted { get; set; }
        public string EngineerGroup { get; set; }
        public string RequestStatus { get; set; }
        public string RequestPhase { get; set; }
        public string ApprovalStatus { get; set; }
        public Nullable<System.DateTime> ApprovalDate { get; set; }
        public Nullable<System.DateTime> ImplementedDate { get; set; }
        public string ResultsOfImp { get; set; }
        public string AdditionalDetail { get; set; }
        public Nullable<bool> SMAutoGenerateTicket { get; set; }
        public Nullable<System.DateTime> SMImpStartDateTime { get; set; }
        public Nullable<System.DateTime> SMImpEndDateTime { get; set; }
        public Nullable<System.DateTime> SMValStartDateTime { get; set; }
        public Nullable<System.DateTime> SMValEndDateTime { get; set; }
        public string SMValidator { get; set; }
    }
}
