//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SourceControl.Models.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestProxy
    {
        public int ID { get; set; }
        public int RequestNumber { get; set; }
        public string TaskOrder { get; set; }
        public string Summary { get; set; }
        public string DiagramLink { get; set; }
    }
}
