//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SourceControl.Models.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestIP
    {
        public int ID { get; set; }
        public int RequestNumber { get; set; }
        public string name { get; set; }
        public string domain { get; set; }
        public string comment { get; set; }
        public string vlan { get; set; }
        public string ASSIGNMENT { get; set; }
        public string ApplicationEnvironment { get; set; }
        public string subnet { get; set; }
        public string Site { get; set; }
    }
}
