//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SourceControl.Models.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Route
    {
        public System.Guid guid { get; set; }
        public System.Guid jobguid { get; set; }
        public string f5Hostname { get; set; }
        public string name { get; set; }
        public string fullpath { get; set; }
        public string gw { get; set; }
        public int mtu { get; set; }
        public string network { get; set; }
    }
}
