//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SourceControl.Models.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class SelfIP
    {
        public System.Guid guid { get; set; }
        public System.Guid jobguid { get; set; }
        public string f5HostName { get; set; }
        public string kind { get; set; }
        public string name { get; set; }
        public string partition { get; set; }
        public string fullPath { get; set; }
        public Nullable<long> generation { get; set; }
        public string selfLink { get; set; }
        public string address { get; set; }
        public string floating { get; set; }
        public string inheritedTrafficGroup { get; set; }
        public string trafficGroup { get; set; }
        public Nullable<long> unit { get; set; }
        public string vlan { get; set; }
        public string allowService { get; set; }
    }
}
