//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SourceControl.Models.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class SiteMap
    {
        public int ID { get; set; }
        public int ParentID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Controller { get; set; }
        public string Action { get; set; }
        public string paramid { get; set; }
        public string URL { get; set; }
        public string Area { get; set; }
        public string Parameter { get; set; }
        public string Module { get; set; }
        public string StatusCode { get; set; }
        public string DisplayOrder { get; set; }
        public string Roles { get; set; }
    }
}
