//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SourceControl.Models.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMJobLog
    {
        public System.Guid Guid { get; set; }
        public System.DateTime startDateTime { get; set; }
        public Nullable<System.DateTime> endDateTime { get; set; }
        public Nullable<bool> Successful { get; set; }
        public string errorDetails { get; set; }
        public Nullable<int> recordCount { get; set; }
        public string jobType { get; set; }
        public Nullable<int> updatedCount { get; set; }
        public Nullable<int> newRecordCount { get; set; }
    }
}
