//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SourceControl.Models.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMTask
    {
        public System.Guid guid { get; set; }
        public System.Guid jobguid { get; set; }
        public System.DateTime lastUpdated { get; set; }
        public string TaskID { get; set; }
        public Nullable<int> ClosureCode { get; set; }
        public string Assignee { get; set; }
        public string AssignmentGroup { get; set; }
        public string Category { get; set; }
        public Nullable<System.DateTime> CloseTime { get; set; }
        public Nullable<System.DateTime> DateEntered { get; set; }
        public Nullable<bool> Open { get; set; }
        public string Originator { get; set; }
        public string ParentChange { get; set; }
        public string Phase { get; set; }
        public Nullable<System.DateTime> PlannedEnd { get; set; }
        public Nullable<System.DateTime> PlannedStart { get; set; }
        public string Reason { get; set; }
        public string Status { get; set; }
        public string Title { get; set; }
        public Nullable<System.DateTime> ScheduledDowntimeEnd { get; set; }
        public Nullable<System.DateTime> ScheduledDowntimeStart { get; set; }
        public Nullable<System.DateTime> ActualEnd { get; set; }
        public Nullable<System.DateTime> ActualStart { get; set; }
        public Nullable<int> Impact { get; set; }
        public Nullable<int> Urgency { get; set; }
    }
}
