//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SourceControl.Models.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class SwitchModule
    {
        public System.Guid ModuleGUID { get; set; }
        public System.Guid DeviceGUID { get; set; }
        public string ModuleNum { get; set; }
        public string ModuleType { get; set; }
        public string SerialNum { get; set; }
        public string Comments { get; set; }
    }
}
