//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SourceControl.Models.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class SwitchPort
    {
        public string DeviceName { get; set; }
        public System.Guid PortGUID { get; set; }
        public string PortNum { get; set; }
        public string PortType { get; set; }
        public Nullable<bool> Connected { get; set; }
        public string HostName { get; set; }
        public string Interface { get; set; }
        public string VLAN { get; set; }
        public string Comments { get; set; }
        public string SwitchLocation { get; set; }
        public string NetworkType { get; set; }
    }
}
