//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SourceControl.Models.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserReport
    {
        public System.Guid guid { get; set; }
        public string username { get; set; }
        public string reportName { get; set; }
        public string frequency { get; set; }
        public string cc { get; set; }
        public Nullable<bool> active { get; set; }
    }
}
