//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SourceControl.Models.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIP
    {
        public System.Guid guid { get; set; }
        public Nullable<System.Guid> jobguid { get; set; }
        public string f5HostName { get; set; }
        public string kind { get; set; }
        public string name { get; set; }
        public string partition { get; set; }
        public string fullPath { get; set; }
        public Nullable<long> generation { get; set; }
        public string selfLink { get; set; }
        public string addressStatus { get; set; }
        public string autoLasthop { get; set; }
        public string cmpEnabled { get; set; }
        public Nullable<long> connectionLimit { get; set; }
        public string destination { get; set; }
        public Nullable<bool> enabled { get; set; }
        public Nullable<long> gtmScore { get; set; }
        public string ipProtocol { get; set; }
        public string mask { get; set; }
        public string mirror { get; set; }
        public string mobileAppTunnel { get; set; }
        public string nat64 { get; set; }
        public string pool { get; set; }
        public string rateLimit { get; set; }
        public Nullable<long> rateLimitDstMask { get; set; }
        public string rateLimitMode { get; set; }
        public Nullable<long> rateLimitSrcMask { get; set; }
        public string source { get; set; }
        public string sourceAddressTranslationType { get; set; }
        public string sourceAddressTranslationPool { get; set; }
        public string sourcePort { get; set; }
        public string synCookieStatusnv { get; set; }
        public string translateAddress { get; set; }
        public string translatePort { get; set; }
        public Nullable<bool> vlansDisabled { get; set; }
        public Nullable<long> vsIndex { get; set; }
        public Nullable<System.Guid> policiesReferenceGuid { get; set; }
        public Nullable<System.Guid> profilesReferenceGuid { get; set; }
        public Nullable<System.Guid> persistGuid { get; set; }
        public string rules { get; set; }
        public string description { get; set; }
        public Nullable<bool> vlansEnabled { get; set; }
        public string vlans { get; set; }
        public Nullable<bool> disabled { get; set; }
        public string PoolName { get; set; }
        public string PoolMonitor { get; set; }
        public string PoolLoadBalancingMode { get; set; }
        public string StatusAvailabilityState { get; set; }
        public string PersistName { get; set; }
        public string PersistType { get; set; }
        public string PersistTimeOut { get; set; }
        public string CertName { get; set; }
        public string CertChain { get; set; }
        public string CertKey { get; set; }
        public string PoolGuid { get; set; }
    }
}
