//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SourceControl.Models.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIPProfilesReference
    {
        public System.Guid guid { get; set; }
        public System.Guid jobguid { get; set; }
        public System.Guid vipguid { get; set; }
        public string vipName { get; set; }
        public string f5HostName { get; set; }
        public string link { get; set; }
        public Nullable<bool> isSubcollection { get; set; }
    }
}
