//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SourceControl.Models.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIPPersistDetail
    {
        public System.Guid guid { get; set; }
        public System.Guid jobguid { get; set; }
        public string f5hostname { get; set; }
        public string persistType { get; set; }
        public string kind { get; set; }
        public string name { get; set; }
        public string partition { get; set; }
        public string fullPath { get; set; }
        public Nullable<long> generation { get; set; }
        public string selfLink { get; set; }
        public string defaultsFrom { get; set; }
        public string hashAlgorithm { get; set; }
        public string mapProxies { get; set; }
        public string mapProxyAddress { get; set; }
        public string mask { get; set; }
        public string matchAcrossPools { get; set; }
        public string matchAcrossServices { get; set; }
        public string matchAcrossVirtuals { get; set; }
        public string mirror { get; set; }
        public string overrideConnectionLimit { get; set; }
        public string timeout { get; set; }
        public string alwaysSend { get; set; }
        public string cookieEncryption { get; set; }
        public string cookieName { get; set; }
        public string expiration { get; set; }
        public Nullable<long> hashLength { get; set; }
        public Nullable<long> hashOffset { get; set; }
        public string method { get; set; }
        public string iRule { get; set; }
    }
}
