//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SourceControl.Models.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class VLAN
    {
        public System.Guid guid { get; set; }
        public System.Guid jobguid { get; set; }
        public string f5Hostname { get; set; }
        public string name { get; set; }
        public string fullpath { get; set; }
        public string autoLasthop { get; set; }
        public string cmpHash { get; set; }
        public string dagRoundRobin { get; set; }
        public string dagTunnel { get; set; }
        public string failsafe { get; set; }
        public string failsafeAction { get; set; }
        public int failsafeTimeout { get; set; }
        public int ifIndex { get; set; }
        public string learning { get; set; }
        public int mtu { get; set; }
        public int tag { get; set; }
    }
}
