//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SourceControl.Models.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class VMPhoneBook
    {
        public System.Guid guid { get; set; }
        public string Environment { get; set; }
        public string ServerName { get; set; }
        public string Mgt_IP { get; set; }
        public string Prod_IP { get; set; }
        public string BUR_IP { get; set; }
        public string SEC_IP { get; set; }
        public string Comment { get; set; }
        public string CPU { get; set; }
        public string RAM { get; set; }
        public string DiskSize { get; set; }
        public string ESXi_Host { get; set; }
    }
}
