//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SourceControl.Models.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebSiteSetting
    {
        public int WebSiteSettingId { get; set; }
        public string WelcomeMessage { get; set; }
        public string BannerLogo { get; set; }
        public string HomePageLogo { get; set; }
        public string CompanyName { get; set; }
    }
}
